name: "dbt_project"
version: "1.0"
config-version: 2

profile: "civitas_brt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  dbt_project:            
    +persist_docs:
      relation: true
      columns: true
    +meta:
      owner: "@ari.cunha"
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: view
